server:
  port: 30000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Elio1024/spring-cloud-config
          username: Elio1024
          password: maxuanmima123
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10001/eureka/,http://peer2:10002/eureka/,http://peer3:10003/eureka/
