server:
  port: 10003

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer2:10002/eureka/,http://peer1:10001/eureka/
spring:
  application:
    name: eureka-server